-- Migration 005: recovery_protocols table
CREATE TABLE recovery_protocols (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  series TEXT NOT NULL,
  modality_type TEXT NOT NULL,
  cns_low_avoid BOOLEAN DEFAULT FALSE,
  off_day_only BOOLEAN DEFAULT FALSE,
  primary_system TEXT NOT NULL,
  secondary_systems TEXT[] DEFAULT '{}',
  iaci_subsystems_targeted TEXT[] DEFAULT '{}',
  target_areas_primary TEXT[] DEFAULT '{}',
  target_areas_secondary TEXT[] DEFAULT '{}',
  benefits TEXT[] DEFAULT '{}',
  equipment_needed TEXT[] DEFAULT '{}',
  evidence_level TEXT,
  dose_min TEXT,
  dose_sweet_spot TEXT,
  dose_upper_limit TEXT,
  instructions TEXT,
  avoid_cautions TEXT,
  ideal_timing TEXT,
  evidence_notes TEXT,
  athlete_tidbit TEXT,
  athlete_caution TEXT,
  protocol_classes TEXT[] DEFAULT '{}',
  phenotypes_recommended TEXT[] DEFAULT '{}',
  phenotypes_avoid TEXT[] DEFAULT '{}',
  environment TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now()
);
